// lib/pictureList.ts
export const pictureList = [
  "/apps/arc.png",
  "/apps/craft.png",
  "/apps/cron.png",
  "/apps/discord.png",
  "/apps/figma.png",
  "/apps/finder.png",
  "/apps/linear.png",
  "/apps/live.png",
  "/apps/mail.png",
  "/apps/messages.png",
  "/apps/music.png",
  "/apps/resolve.png",
  "/apps/safari.png",
  "/apps/screenflow.png",
  "/apps/slack.png",
  "/apps/telegram.png",
  "/apps/tower.png",
  "/apps/vscode.png",
  "/apps/warp.png",
  "/apps/webstorm.png",
  "/apps/wechat.png",
];
